### PR TITLE
added jetpack gravity alignment plugin

### PR DESCRIPTION
**Pull request by thejoun**
Have a great day :)

### CODE REVIEW

**Comment by austinvaness** [comment]
This would break in multiplayer right? You might want to put a check in so that it is singleplayer only.

**Comment by thejoun** [comment]
I just tested it with my friend in multiplayer and it seemed to work perfectly fine on both sides.

**Comment by austinvaness** [comment]
Were you the host in that situation? I don't think you can set the matrix of the character as a multiplayer client.

**Comment by thejoun** [comment]
I was the client

**Pull request merged**
