### PR TITLE
Create VSIRecolorableThrusters.xml

### PR DESCRIPTION
**Pull request by Arstraea**

### CODE REVIEW

**Comment by viktor-ferenczi** [comment]
@austinvaness How can we test whether this mod plugin work with multiplayer servers without having to add it to the PluginHub? Is there a way to add it only locally for testing?

I suspect this mod will not work if not added to the world, since the thruster flame color must be stored with the thruster block itself, which happens on server side. While the UI change may show up the flame color would not be stored. - In theory. We need to test it.

Such testing ability would be useful in case of mod plugins with such arguably server side functionality.

**Comment by jihun-ninenjoy** [comment]
You're right. I forgot that flame color information is stored in each thruster's CustomData.
I just thought it's just changing visual.

And I also wonder is there a way to test specific mod locally.

**Comment by Arstraea** [comment]
You're right. I forgot that flame color information is stored in each thruster's CustomData.
I just thought it's just changing visual.

And I also wonder is there a way to test specific mod locally.

**Comment by zznty** [comment]
if mod will store the data inside custom data field then it can be clientside only, but as i remember its using mod storage which requires mod to be loaded server side.

**Comment by skybleu** [comment]
This plugin would still be useful even if other players do not see my set Color's.
I don't care if other users see my thruster flames differently, it's for my personal aesthetic pleasure and for blueprints I export to look nice once when they move to/from players with mod or plugin.

**Comment by Arstraea** [comment]
Yeah. Thruster's color has no impact to other's play. It's only personal aesthetic feature.
But @austinvaness close this pull request, I don't know exact reason but seems it has server-side issue.

**Pull request closed without merging**
